#
# Copyright (c) 2019 Wee Loong Kuan
#
# BareMetalLib is based on libc++ (https://libcxx.llvm.org/).
# 
# This file is licensed under under the Apache License v2.0 with LLVM Exceptions. For more details,
# see the LICENSE.md file in the top-level directory of this distribution, or copy at 
# https://llvm.org/LICENSE.txt.
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#

language: cpp

os: linux
dist: xenial
sudo: required
services:
  - docker

env:
  - DOCKER_CXX: /usr/bin/clang++-6.0
    DOCKER_TAG: linux-x86_64
  - DOCKER_CXX: /usr/bin/g++-8
    DOCKER_TAG: linux-x86_64

before_install:
  - sudo docker pull kuanweeloong/bml-build:${DOCKER_TAG}
  - >-
    sudo docker create --rm --name bml-travis --env CXX=${DOCKER_CXX}
    kuanweeloong/bml-build:${DOCKER_TAG}
  - sudo docker cp . bml-travis:/bml/src/

script:
  - sudo docker start --attach bml-travis
